version: '3'
services:
  elasticsearch:
    image: elasticsearch:2.4.4
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Dmapper.allow_dots_in_name=true"
    ports:
      - "9200:9200"
  web:
    build: .
    command: bash -c 
      "padrino start -h 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - ES_URI=elasticsearch
      - RACK_ENV=test # Set env to ensure ES configs with replicas 0
    depends_on:
      - elasticsearch