# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby
env: 
  ES_JAVA_OPTS: "-Dmapper.allow_dots_in_name=true"
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
  BUNDLE_PATH: vendor/bundle
  RACK_ENV: test
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Setup ElasticSearch
      uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: 2.4.4

    - name: Install dependencies
      run: bundle install
    - name: Wait for Elasticsearch
      run: |
        while ! curl -sS --fail http://localhost:9200 > /dev/null 2>&1; do
          sleep 5
        done

    - name: Create Test Directory
      run: mkdir ~/rspec  
    
    - name: RSpec
      run: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml

    - name: Save assets
      uses: actions/upload-artifact@v2
      with:
        name: test-output
        path: ~/rspec
